FROM apache/spark:3.5.0

USER root

RUN mkdir -p /home/spark/.ivy2/cache && \
    chown -R spark:spark /home/spark && \
    chmod -R 777 /home/spark

USER spark

WORKDIR /app
COPY spark_app.py .

CMD ["/opt/spark/bin/spark-submit",\
     "--conf", "spark.jars.ivy=/home/spark/.ivy2",\
     "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.postgresql:postgresql:42.7.1",\
     "/app/spark_app.py"]
